# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fake_item',
            name='api_verison',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='fake_item',
            name='behot_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fake_item',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fake_item',
            name='status',
            field=models.SmallIntegerField(),
        ),
    ]
