# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_web', '0002_auto_20160808_0248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fake_item',
            old_name='api_verison',
            new_name='api_version',
        ),
        migrations.AlterField(
            model_name='item_type',
            name='items',
            field=models.ManyToManyField(blank=True, to='manage_web.fake_item'),
        ),
    ]
